### ISSUE TITLE
Tracking: Game-readiness of @react-three/jolt

### ISSUE THREAD

**Issue by DennisSmolek** [pmndrs/react-three-jolt#51]
This is a clone of the [original issue in r3/Rapier](https://github.com/pmndrs/react-three-rapier/issues/92)

Some of these things are done already because we ported them from r3/rapier, however they need full testing and likely adjustments. 

Must Have:

- [ ]  Make update priority configurable.
- [ ]   Clamp deltatime values to 1s max. 
 - [ ]  ither provide interpolation for translation (currently disabled), or allow the user to configure a varying time step. (Currently, using a lerping follow camera immediately makes the non-interpolated "jumpy" nature of rigidbody movements very obvious.)
 - [ ]  Allow the user to use sensors.
 - [ ]  Allow setting of restrictRotations and restrictTranslations on rigidbodies. 

Should Have:
 - [ ]  Allow for per-collider collision callbacks.
- [ ]   Easy convex collider generation from any geometry, including loaded GLTFs.
 - [ ]  Allow the user to specify the density of colliders (or a default value on RigidBody.) (Rapier is nice in that it will automatically calculate the mass from the density and the volume of the colliders.)
 - [ ]  Allow the user to access a rigidbody's scene object through the ref/API. (RigidBodies wrap their children in an <object3D> scene object, but don't expose them through their API. Systems that need to interact with the scene object currently only have the option of establishing their own wrapper object and storing the ref to that separately.)
- [ ]   The RigidBodyApi should not force bodies that it interacts with to wake up. This decision should be left to the user (but it would be fine to default this to true.) (https://github.com/pmndrs/react-three-rapier/pull/125)
 - [ ]  The scene object created by RigidBodies and Colliders should default to matrixAutoUpdate={false}, and have their matrices updated explicitly (or this attribute toggled) when the owning rigidbody is awake (ie. not sleeping).
    - Sleeping bodies will never move, so disabling their automatic matrix recalculations is a good optimizations for scenes with larger amounts of rigid bodies (a large portion of which might be sleeping.)
    - It'd be okay to make this optimization opt-in
Nice to Have:
 - [ ]  Easy to use physics debugger
